### ISSUE TITLE
Que hace este programa

### ISSUE THREAD

**Issue by Kicho-Fops** [aitana-programming/cmamo_en_C#1]
Hola buenos días, me interesa usar este programa un un software que estoy desarrollando pero no aparece que es lo que hace, no tiene documentación, no se si pudieran explicarme que hace cada parte del proyecto

**Comment by aitana-programming** [comment]
NO
Saludos :3 🥉 
![arrival-cat](https://github.com/aitana-programming/cmamo_en_C/assets/49791184/ea13af4f-5ca1-425b-b381-4d161f9eb336)
